#### Things to learn/Practice
- Python's list being too slow ie the reason why numpy is used 
> Advanced Numpy (reshape , concatenate, splitting , hsplit,vsplit) etc


- concatenate Most general function, concatenates collection of arrays along one axis
- vstack, row_stack Stack arrays row-wise (along axis 0)
- hstack Stack arrays column-wise (along axis 1)
- column_stack Like hstack, but converts 1D arrays to 2D column vectors first
- dstack Stack arrays “depth”-wise (along axis 2)
- split Split array at passed locations along a particular axis
- hsplit/vsplit Convenience functions for splitting on axis 0 and 1, respectively

In [1]:
import numpy as np

In [2]:
ints = np.ones(10, dtype=np.uint16)

In [3]:
ints

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=uint16)

In [4]:
floats = np.ones(10, dtype=np.float32)

In [5]:
floats

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
#default dtype is float
ten=np.ones((10,5),dtype=np.uint16)


In [15]:
ten

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint16)

In [16]:
np.ones((3,4,5),dtype=np.float64).strides
#3 layers (or 2D planes).
#Each layer has 4 rows.
#Each row has 5 columns.

(160, 40, 8)

In [18]:
64*5

320

In [19]:
np.issubdtype(ints.dtype, np.integer)


True

In [21]:
# mro of parent class of specific dtype
np.float64.mro()

[numpy.float64,
 numpy.floating,
 numpy.inexact,
 numpy.number,
 numpy.generic,
 float,
 object]

In [22]:
np.uint64.mro()

[numpy.uint64,
 numpy.unsignedinteger,
 numpy.integer,
 numpy.number,
 numpy.generic,
 object]

In [34]:
arr=np.arange(8)
arr=np.random.randn(100)

In [35]:
arr

array([-0.70800328, -0.76702512,  0.42282896,  0.4587373 ,  0.08953659,
       -0.77991286,  0.56335903, -0.02393853,  0.15446525,  0.05451344,
       -0.21881846, -1.12774511, -0.10899095,  2.29786013, -1.30771521,
       -1.51294311, -1.80721372,  0.89269774,  0.60579202, -0.47363302,
       -0.65091121,  0.48485265, -0.98478315, -0.62644444,  0.23473509,
       -0.22503499, -0.51723071, -0.73642257,  0.45784558, -0.09257439,
       -0.52983275,  0.62558174, -0.45370825,  0.26494412, -0.89444485,
       -1.88665285, -1.39714914,  0.09320848, -0.3217302 , -1.40541443,
        0.34022465, -1.49187912,  0.02058817,  0.87068318, -0.2115463 ,
        0.81861731,  0.68224007, -0.19448593,  0.93271516,  0.70539088,
       -2.0643401 , -0.49141506,  0.21019558, -1.42849623,  0.88087123,
       -0.33548141, -0.03566885, -1.90300446, -0.10085763,  0.815182  ,
       -0.31754111, -0.54084338, -0.95980519,  0.91741805,  0.1157997 ,
       -1.9742234 , -0.43757593, -1.07654062,  1.54361672, -0.54

In [37]:
arr.dtype

dtype('float64')

In [41]:
arr=np.arange(10)## reshpe like this 5*2 2*5
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr.reshape((5,2),order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [43]:
arr.reshape((5, 2)).reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
arr.reshape((5,-1))
## -1 se horizontal count 

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [45]:
# .ravel()
# it transforms a multi-dimensional array into a one-dimensional array without making a copy of the original data whenever possible
#When NumPy's .ravel() function is said to return a view of the original data "without making a copy," it means that the flattened array shares the same memory as the original array. Changes to the flattened array will affect the original array and vice versa, as no new data is created. This is efficient in terms of memory and performance.
arr.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# opposite of ravel() flatten do same work but insted it returns a copy of data
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
# 'C' - row 'F' - col
arr.ravel('C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
arr=np.arange(12).reshape(6,2)

In [58]:
arr.ravel('f')

array([ 0,  2,  4,  6,  8, 10,  1,  3,  5,  7,  9, 11])

In [59]:
arr.ravel('C')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])
#Axis 0: Refers to the rows. Operations with axis=0 are performed down the rows (i.e., column-wise).
#Axis 1: Refers to the columns. Operations with axis=1 are performed across the columns (i.e., row-wise).
arr=np.concatenate([arr1,arr2],axis=1)

In [63]:
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [64]:
np.vstack((arr1,arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [65]:
np.hstack((arr1,arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [68]:
arr = np.arange(6)
arr1 = arr.reshape((3, 2))
arr2 = np.random.randn(3, 2)
np.r_[arr1, arr2]

array([[ 0.        ,  1.        ],
       [ 2.        ,  3.        ],
       [ 4.        ,  5.        ],
       [-0.47215545,  0.35798425],
       [ 1.62114349,  0.01591892],
       [ 0.73885311,  1.17076688]])


- np.r_: Concatenates arrays along the first axis (row-wise) or creates arrays with slices.
- np.c_: Concatenates arrays along the second axis (column-wise).
- np.dstack: Stacks arrays along the third axis (depth-wise).

In [69]:
np.c_[arr1, arr2]

array([[ 0.        ,  1.        , -0.47215545,  0.35798425],
       [ 2.        ,  3.        ,  1.62114349,  0.01591892],
       [ 4.        ,  5.        ,  0.73885311,  1.17076688]])

In [70]:
arr.repeat(3)

array([0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5])

In [72]:
arr = np.random.randn(2, 2)
arr.repeat(2, axis=0)

array([[-0.51051607, -0.71302902],
       [-0.51051607, -0.71302902],
       [ 0.39926625,  0.71413309],
       [ 0.39926625,  0.71413309]])

In [ ]:
#Note that if no axis is passed, the array will be flattened first, which is likely not whatyou want. Similarly, you can pass an array of integers when repeating a multidimen‐sional array to repeat a given slice a different number of times:

In [73]:
np.tile(arr,(2,1))

array([[-0.51051607, -0.71302902],
       [ 0.39926625,  0.71413309],
       [-0.51051607, -0.71302902],
       [ 0.39926625,  0.71413309]])

In [74]:
np.tile(arr,(2,2))

array([[-0.51051607, -0.71302902, -0.51051607, -0.71302902],
       [ 0.39926625,  0.71413309,  0.39926625,  0.71413309],
       [-0.51051607, -0.71302902, -0.51051607, -0.71302902],
       [ 0.39926625,  0.71413309,  0.39926625,  0.71413309]])

In [79]:
# Take and put
arr = np.arange(10) * 100
print(arr)
inds = [7, 1, 2, 6]
arr[inds]


[  0 100 200 300 400 500 600 700 800 900]


array([700, 100, 200, 600])

In [80]:
arr.put(inds, [40, 41, 42, 43])
# these vals 40,41 will go to their destined indices

In [81]:
arr

array([  0,  41,  42, 300, 400, 500,  43,  40, 800, 900])

In [83]:
arr.take(inds, axis=0)

array([40, 41, 42, 43])

In [85]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

indices = [0, 2]
result = np.take(arr, indices, axis=1)
print(result)

[[10 30]
 [40 60]
 [70 90]]


In [89]:
ind=[3,4]
arr.put(ind, [43,45])


In [91]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

In [92]:
ind=[8]
arr.put(ind,[45])


In [93]:
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 45]])

In [94]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

# Splitting the array into 3 sub-array vertically
sub_arrays = np.vsplit(arr, 3)

print(sub_arrays)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [95]:
sub_arrays=np.hsplit(arr,4)

In [96]:
sub_arrays

[array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]]),
 array([[ 4],
        [ 8],
        [12]])]