 # Numpy

In [83]:
import numpy as np

In [84]:
zeros_array = np.zeros(10)
ones_array = np.ones(10)
print(zeros_array,ones_array)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [87]:
# arange func()-> to generate a range of numbers
range_array = np.arange(20)
print(range_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [91]:
array1 = np.random.rand(10)
array2 = np.random.rand(10)

add = array1 + array2
sub = array1 - array2
mul = array1 * array2

print("Addition: \n", add)
print("Subtraction: \n", sub)
print("Multiplication:\n", mul)

Addition: 
 [0.40131681 0.87134743 1.95813617 1.2456861  0.87726083 0.33641361
 1.37886153 0.55179676 0.99142501 1.62165776]
Subtraction: 
 [-0.19667529  0.58847367 -0.03949541  0.00194946 -0.80784133  0.00962842
 -0.0344799  -0.31802075 -0.27183522  0.06963376]
Multiplication:
 [0.0305935  0.10323627 0.95818434 0.38793252 0.02924474 0.02827035
 0.47501757 0.05083562 0.22725729 0.65623126]


In [93]:
array = np.random.rand(10)

sum_array = np.sum(array)
mean_array = np.mean(array)
std_array = np.std(array)
abs=np.absolute(2-3)

print("Sum:", sum_array)
print("Mean:", mean_array)
print("Standard Deviation:", std_array)
print("ABS:", abs)

Sum: 5.75497585446083
Mean: 0.575497585446083
Standard Deviation: 0.31991722116530225
ABS: 1


In [94]:
matrix = np.arange(9).reshape(3, 3)
reshaped_array = matrix.flatten()
# to flatten to convert it to 1-d array
print("Original matrix:\n", matrix)
print("Reshaped array:", reshaped_array)

Original matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Reshaped array: [0 1 2 3 4 5 6 7 8]


In [101]:
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

vertical_concat = np.vstack((array1, array2))
horizontal_concat = np.hstack((array1, array2))# horizontal stack we also do it 
print("Vertical Concatenation: \n", vertical_concat)
print("Horizontal Concatenation: \n", horizontal_concat)

Vertical Concatenation: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontal Concatenation: 
 [[1 2 5 6]
 [3 4 7 8]]


In [103]:
array = np.arange(10)
even_numbers = array[::2]
odd_numbers = array[::3]
print("Even numbers:", even_numbers ,"\n","Odd numbers:",odd_numbers)

Even numbers: [0 2 4 6 8] 
 Odd numbers: [0 3 6 9]


# Pandas

In [28]:
import pandas as pd

In [29]:
df=pd.read_csv('honey.csv')

In [30]:
df.columns

Index(['state', 'numcol', 'yieldpercol', 'totalprod', 'stocks', 'priceperlb',
       'prodvalue', 'year'],
      dtype='object')

In [31]:
df.head()

state    numcol  yieldpercol   totalprod      stocks  priceperlb  \
0    AL   16000.0           71   1136000.0    159000.0        0.72   
1    AZ   55000.0           60   3300000.0   1485000.0        0.64   
2    AR   53000.0           65   3445000.0   1688000.0        0.59   
3    CA  450000.0           83  37350000.0  12326000.0        0.62   
4    CO   27000.0           72   1944000.0   1594000.0        0.70   

    prodvalue  year  
0    818000.0  1998  
1   2112000.0  1998  
2   2033000.0  1998  
3  23157000.0  1998  
4   1361000.0  1998

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 626 entries, 0 to 625
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   state        626 non-null    object 
 1   numcol       626 non-null    float64
 2   yieldpercol  626 non-null    int64  
 3   totalprod    626 non-null    float64
 4   stocks       626 non-null    float64
 5   priceperlb   626 non-null    float64
 6   prodvalue    626 non-null    float64
 7   year         626 non-null    int64  
dtypes: float64(5), int64(2), object(1)
memory usage: 39.2+ KB


In [78]:
df.isnull().sum()

state          0
numcol         0
yieldpercol    0
totalprod      0
stocks         0
priceperlb     0
prodvalue      0
year           0
dtype: int64

In [81]:
df.duplicated().sum()

0

In [105]:
df['state'][::2]

0      AL
2      AR
4      CO
6      GA
8      ID
       ..
616    SD
618    TX
620    VT
622    WA
624    WI
Name: state, Length: 313, dtype: object

In [107]:
#k-1 hot encoding can eb done thorugh pandas but it's not preferred approach
pd.get_dummies(df,columns=['state','year'],drop_first=True)

numcol  yieldpercol   totalprod      stocks  priceperlb   prodvalue  \
0     16000.0           71   1136000.0    159000.0        0.72    818000.0   
1     55000.0           60   3300000.0   1485000.0        0.64   2112000.0   
2     53000.0           65   3445000.0   1688000.0        0.59   2033000.0   
3    450000.0           83  37350000.0  12326000.0        0.62  23157000.0   
4     27000.0           72   1944000.0   1594000.0        0.70   1361000.0   
..        ...          ...         ...         ...         ...         ...   
621    4000.0           41    164000.0     23000.0        3.77    618000.0   
622   62000.0           41   2542000.0   1017000.0        2.38   6050000.0   
623    6000.0           48    288000.0     95000.0        2.91    838000.0   
624   60000.0           69   4140000.0   1863000.0        2.05   8487000.0   
625   50000.0           51   2550000.0    459000.0        1.87   4769000.0   

     state_AR  state_AZ  state_CA  state_CO  ...  year_2003  year_2004  \
0       False     False     False     False  ...      False      False   
1       False      True     False     False  ...      False      False   
2        True     False     False     False  ...      False      False   
3       False     False      True     False  ...      False      False   
4       False     False     False      True  ...      False      False   
..        ...       ...       ...       ...  ...        ...        ...   
621     False     False     False     False  ...      False      False   
622     False     False     False     False  ...      False      False   
623     False     False     False     False  ...      False      False   
624     False     False     False     False  ...      False      False   
625     False     False     False     False  ...      False      False   

     year_2005  year_2006  year_2007  year_2008  year_2009  year_2010  \
0        False      False      False      False      False      False   
1        False      False      False      False      False      False   
2        False      False      False      False      False      False   
3        False      False      False      False      False      False   
4        False      False      False      False      False      False   
..         ...        ...        ...        ...        ...        ...   
621      False      False      False      False      False      False   
622      False      False      False      False      False      False   
623      False      False      False      False      False      False   
624      False      False      False      False      False      False   
625      False      False      False      False      False      False   

     year_2011  year_2012  
0        False      False  
1        False      False  
2        False      False  
3        False      False  
4        False      False  
..         ...        ...  
621      False       True  
622      False       True  
623      False       True  
624      False       True  
625      False       True  

[626 rows x 63 columns]

# Seaborn

In [9]:
import seaborn as sns

# Scikit-learn

In [33]:
from sklearn.model_selection import train_test_split

In [54]:
X_train.shape,y_train.shape

((500, 7), (500,))

# Now we will standardize the numeric cols and apply encoder on string dtype cols

- state col is nominal so we will apply OneHotEncoder, for other numeircal col we will use standardscaler

In [62]:
features = ['state', 'numcol', 'yieldpercol', 'stocks', 'priceperlb', 'prodvalue', 'year']
target = 'totalprod'

# Splitting data into train and test sets
X = df[features]
y = df[target]

In [69]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['totalprod']),
                                                      df['totalprod'],
                                                       test_size=0.2,
                                                       random_state=42)

In [41]:
from sklearn.preprocessing import OneHotEncoder
categorical_transformer = OneHotEncoder()

In [55]:
numeric_features = ['numcol', 'yieldpercol', 'stocks', 'priceperlb', 'prodvalue', 'year']
categorical_features = ['state']

In [70]:
from sklearn.preprocessing import StandardScaler
numeric_transformer = StandardScaler()

In [65]:
from sklearn.compose import ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)])


In [74]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()


In [75]:
from sklearn.pipeline import Pipeline
model = Pipeline(steps=[('preprocessor', preprocessor),
                        ('regressor', LinearRegression())])

In [76]:
model.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['numcol', 'yieldpercol',
                                                   'stocks', 'priceperlb',
                                                   'prodvalue', 'year']),
                                                 ('cat', OneHotEncoder(),
                                                  ['state'])])),
                ('regressor', LinearRegression())])

In [77]:
y_pred = model.predict(X_test)

# Evaluate
print('Mean Squared Error:', mean_squared_error(y_test, y_pred))
print('R-squared:', r2_score(y_test, y_pred))

Mean Squared Error: 1426825956357.5918
R-squared: 0.960866793984287
