In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.16.1


In [3]:
### initialization
x=tf.constant(4.0,shape=(1,1),dtype=tf.float32)
x

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[4.]], dtype=float32)>

In [4]:
#2-d tensor
x=tf.constant([[1,2,3],[4,5,6]])
x

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [5]:
x=tf.ones(2,3)#2,3 is ignored so it's just this array
x
#As a result, it creates a tensor of shape (2,) with two ones: [1, 1].

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 1])>

In [6]:
x=tf.ones((2,3))
x
##The correct way to specify a shape is by passing a tuple

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [7]:
x=tf.ones(())
x

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [8]:
x=tf.eye(3)
x##identity matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [9]:
x=tf.random.normal((3,3),mean=0,stddev=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.1375313 ,  0.7068329 ,  0.02155145],
       [-0.28060892,  0.06170724,  1.695595  ],
       [-0.16266826, -0.22679251, -0.9693696 ]], dtype=float32)>

In [10]:
x=tf.random.uniform((3,3),minval=0,maxval=1)
x

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.7764387 , 0.06015766, 0.05602527],
       [0.53349626, 0.4280157 , 0.41022408],
       [0.00868344, 0.6259872 , 0.31045973]], dtype=float32)>

In [11]:
x=tf.range(start=2,limit=30,delta=2)
x 

<tf.Tensor: shape=(14,), dtype=int32, numpy=array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])>

In [12]:
 x=tf.cast(x,dtype=tf.float64)

In [13]:
x

<tf.Tensor: shape=(14,), dtype=float64, numpy=
array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28.])>

In [14]:
x=tf.cast(x,dtype=tf.bool)
x
    

<tf.Tensor: shape=(14,), dtype=bool, numpy=
array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])>

In [15]:
## mathematical operations

In [16]:
x=tf.constant(([1,2,3],[4,5,6]))
y=tf.constant(([7,8,9],[10,11,12]))

In [17]:
x,y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]])>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 7,  8,  9],
        [10, 11, 12]])>)

In [18]:
x+y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 8, 10, 12],
       [14, 16, 18]])>

In [19]:
x*y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7, 16, 27],
       [40, 55, 72]])>

In [20]:
x/y

<tf.Tensor: shape=(2, 3), dtype=float64, numpy=
array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])>

In [21]:
add=tf.add(x,y)
sub=tf.subtract(x,y)
mul=tf.multiply(x,y)
div=tf.divide(x,y)
print(add,sub,mul,div)

tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32) tf.Tensor(
[[-6 -6 -6]
 [-6 -6 -6]], shape=(2, 3), dtype=int32) tf.Tensor(
[[ 7 16 27]
 [40 55 72]], shape=(2, 3), dtype=int32) tf.Tensor(
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]], shape=(2, 3), dtype=float64)


In [22]:
y_transposed = tf.transpose(y)  # Now y has shape (3, 2)

result = tf.matmul(x, y_transposed)
print(result)

tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)


In [23]:
result_x = tf.tensordot(x, y, axes=[[1], [1]])
print(result_x)

tf.Tensor(
[[ 50  68]
 [122 167]], shape=(2, 2), dtype=int32)


Matrix multiplication involves taking the dot product of rows from the first matrix with columns from the second matrix. For two matrices A and B, where:

A has shape (m, n) (meaning m rows and n columns)
B has shape (n, p) (meaning n rows and p columns)

In [24]:
z=tf.reduce_sum(x*y,axis=0)

In [25]:
z

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([47, 71, 99])>

In [29]:
x = tf.constant([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
y = tf.constant([[7, 8], [9, 10], [11, 12]])  # Shape (3, 2)

z = x @ y 
print(z)
# @ is the sign for matmul

tf.Tensor(
[[ 58  64]
 [139 154]], shape=(2, 2), dtype=int32)


In [30]:
z=tf.matmul(x,y)
z 
#matmul matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]])>

In [ ]:
###Indexing

In [32]:
x=tf.constant([0,1,2,2,3,4,5,6])

In [33]:
x[:]

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([0, 1, 2, 2, 3, 4, 5, 6])>

In [36]:
x[3]

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [37]:
x[1:3]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2])>

In [38]:
x[-1]

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [39]:
x[1:]

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([1, 2, 2, 3, 4, 5, 6])>

In [40]:
x[::3]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([0, 2, 5])>

In [55]:
y=tf.constant([10,2,3,4,3])


In [56]:
indices = tf.constant([2, 4])
gather = tf.gather(y, indices)
print(gather)
### jo indiecs diye ahin whaan se data utha ke layegha

tf.Tensor([3 3], shape=(2,), dtype=int32)


In [51]:
gather

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 2])>

In [57]:
x=tf.constant(([1,2,3],[4,5,6]))

In [62]:
x[1:,]

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[4, 5, 6]])>

In [65]:
## reshaping

x=tf.range(9)

In [66]:
x=tf.reshape(x,(3,3))

In [67]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [74]:
x=tf.transpose(x,perm=[0,1])

In [75]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>

In [76]:
x=tf.transpose(x,perm=[1,0])
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>